"""Run the pipeline over a fixed set of topics and save every output.

Nothing here is edited by hand: each run is written to samples/ as JSON (full
trace: research, directions, every draft and the editor's verdicts) and as
Markdown for reading. The web app's "Sample scripts" view reads the same files.

    python make_samples.py            # regenerate every sample
    python make_samples.py --only 1,3 # regenerate just these; the rest stay as saved

A sample can name a format ("ranked countdown"): that stands in for a user
clicking that direction card in the UI. Otherwise the recommended card is used.
"""

import argparse
import json
import re
import time
from dataclasses import dataclass
from pathlib import Path

from engine.export import outcome_to_dict, outcome_to_markdown
from engine.llm import OpenAILLM
from engine.pipeline import MAX_REVISIONS, run
from engine.schemas import Brief

OUT_DIR = Path(__file__).parent / "samples"


@dataclass(frozen=True)
class Sample:
    brief: Brief
    format: str | None = None


# One topic per niche, covering all three runtimes and five different tones.
SAMPLES = [
    Sample(Brief("Food & restaurants", "top 5 pizzas in LA", 60, "conversational"), format="ranked countdown"),
    Sample(Brief("Travel", "best beaches in Dubai", 30, "energetic")),
    Sample(Brief("Personal finance", "why your pay rise disappears within three months", 45, "calm expert")),
    Sample(Brief("Fitness", "why you're not getting stronger even though you train every day", 45, "blunt"), format="confession or mistake"),
    Sample(Brief("Tech", "three iPhone settings you should turn off right now", 30, "conversational")),
]


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:50]


def stem_for(n: int, sample: Sample) -> str:
    return f"{n:02d}-{slug(sample.brief.topic)}"


def generate(sample: Sample, llm: OpenAILLM) -> dict:
    record = outcome_to_dict(run(sample.brief, llm, required_format=sample.format), model=llm.model)
    record["requested_format"] = sample.format
    return record


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--only", help="Comma-separated sample numbers to regenerate, e.g. 1,3")
    args = parser.parse_args()
    only = {int(n) for n in args.only.split(",")} if args.only else None

    OUT_DIR.mkdir(exist_ok=True)
    llm = OpenAILLM()
    stems = [stem_for(n, s) for n, s in enumerate(SAMPLES, 1)]

    for n, (sample, stem) in enumerate(zip(SAMPLES, stems), 1):
        if only and n not in only:
            continue
        path = OUT_DIR / f"{stem}.json"
        print(f"[{n}/{len(SAMPLES)}] {sample.brief.niche}: {sample.brief.topic} ({sample.brief.target_seconds}s)", flush=True)
        started = time.perf_counter()
        record = generate(sample, llm)
        record["generation_seconds"] = round(time.perf_counter() - started, 1)
        record["max_revisions"] = MAX_REVISIONS
        path.write_text(json.dumps(record, indent=2, ensure_ascii=False))
        (OUT_DIR / f"{stem}.md").write_text(outcome_to_markdown(record))
        print(
            f"    {record['stats']['words']['total']} words ≈ {record['stats']['seconds']}s · "
            f"{len(record['drafts'])} draft(s) · {len(record.get('research', []))} sourced facts · "
            f"{record['generation_seconds']}s",
            flush=True,
        )

    # Samples whose topic was replaced leave stale files behind; remove them.
    for old in OUT_DIR.glob("[0-9][0-9]-*"):
        if old.stem not in stems:
            old.unlink()

    lines = ["# Sample outputs", "", "Generated by `python make_samples.py`, saved exactly as produced.", ""]
    for stem in stems:
        path = OUT_DIR / f"{stem}.json"
        if path.exists():
            r = json.loads(path.read_text())
            i = r["input"]
            lines.append(f"- [{i['topic']}]({stem}.md): {i['niche']}, {i['target_seconds']}s, {i['tone']}")
    (OUT_DIR / "README.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
